### ISSUE TITLE
File named weights.npz is not saved in the trainning stage.

### ISSUE THREAD

**Issue by WanyiLi** [dimatura/voxnet#1]
I trained model by running commands:
cd scripts/
python train.py config/shapenet10.py shapenet10_train.tar
, after about 11 hours, training is done, a file named metrics.jsonl is generated, but weights.npz does not exist.

**Comment by dimatura** [comment]
That's strange. Did you get any error messages?

**Comment by WanyiLi** [comment]
There is no error messages. I will try again and tell you the results once training stage is completed.

**Comment by dimatura** [comment]
Well, you should actually see a weights.npz as soon as the 4000th iteration (controlled by `checkpoint_every_nth` parameter in `config/shapenet10.py`), and this should happen relatively quickly. I suspect some platform-dependent issue. What's your OS?

**Comment by dimatura** [comment]
Ok, no. This was a dumb bug where it would only save `weights.npz` if it already existed. I pushed a fix. Thanks for reporting this!

**Comment by WanyiLi** [comment]
This problem  still remains in my second try.  The last four rows of output info are as follows:
2015-12-03 05:14:31,401 INFO| epoch: 79, itr: 119735, loss: 0.175494343042, acc: 1.0
2015-12-03 05:14:39,407 INFO| epoch: 79, itr: 119760, loss: 0.202853962779, acc: 0.96875
2015-12-03 05:14:39,434 INFO| training done
2015-12-03 05:14:39,437 INFO| saving 8 parameters to weights.npz

and then I  run ls to list all files, weight.npz is not found.
wyli@wyli-Precision-M4800:~/文档/open_code_cvml/code_deeplearning/voxnet-master/scripts$ ls
config          out.npz         **temp**.png
convert_shapenet10.py   output_viz.py       test.py
download_shapenet10.sh  shapenet10_test.tar train.py
metrics.jsonl       shapenet10_train.tar    train_reports.py
out.html        shapenet10_weights.npz

**Comment by dimatura** [comment]
Did you try the most recent version? I committed a change that should fix this problem.

**Comment by WanyiLi** [comment]
I will try the most commited version. Thanks  a lot!

**Comment by WanyiLi** [comment]
Yes, the new committed version works!
